version: '3.8'
services:
  web-example01:
    build: ./web
    networks:
      - webnetwork

  web-example02:
    build: ./web
    networks:
      - webnetwork

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - web-example01
      - web-example02
    networks:
      - webnetwork

  ab:
    build: ./ab
    networks:
      - webnetwork
    depends_on:
      - nginx

networks:
  webnetwork:
    driver: bridge
